FROM dunglas/frankenphp:1-php8.2-bookworm

WORKDIR /app

RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini

RUN install-php-extensions mysqli

COPY . /app

EXPOSE 80

CMD ["frankenphp", "run", "--config", "/app/Caddyfile"]