<?php
require_once 'config/database.php';require_once 'includes/auth.php';
$logged=isLoggedIn();
$total=(int)$conn->query("SELECT COUNT(*) n FROM reports WHERE status='VERIFIED'")->fetch_assoc()['n'];
$found=(int)$conn->query("SELECT COUNT(*) n FROM reports WHERE status='VERIFIED' AND type='FOUND'")->fetch_assoc()['n'];
$lost=(int)$conn->query("SELECT COUNT(*) n FROM reports WHERE status='VERIFIED' AND type='LOST'")->fetch_assoc()['n'];
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Lost & Found Kampus</title><link rel="stylesheet" href="/assets/app.css">
<style>
.landing{min-height:100vh;background:#10244d;color:#fff}.land-nav{height:72px;display:flex;align-items:center;justify-content:space-between;padding:0 6%;background:#10244d}.land-logo{font-weight:800;font-size:16px;line-height:1.1;display:flex;gap:8px;align-items:center}.land-links{display:flex;align-items:center;gap:22px;font-size:12px}.land-links a{color:#fff;text-decoration:none}.land-hero{min-height:430px;background:linear-gradient(105deg,#10244d 0%,#17396f 58%,#214b88 100%);display:grid;grid-template-columns:1fr 1fr;gap:35px;align-items:center;padding:55px 8%;overflow:hidden;position:relative}.land-hero:after{content:"";position:absolute;width:450px;height:450px;border-radius:50%;right:-100px;bottom:-260px;background:rgba(102,167,255,.16)}.land-hero h1{font-size:43px;line-height:1.05;max-width:530px;margin:0 0 17px}.land-hero p{font-size:13px;line-height:1.7;color:#d0dcf5;max-width:560px}.land-actions{display:flex;gap:10px;margin-top:23px}.land-visual{height:310px;display:flex;align-items:center;justify-content:center;position:relative}.orb{width:185px;height:185px;border:12px solid #b7d5ff;border-radius:50%;box-shadow:0 0 0 18px rgba(183,213,255,.08),0 0 50px rgba(111,173,255,.3);position:relative;animation:float 4s ease-in-out infinite}.orb:after{content:"";position:absolute;width:70px;height:15px;background:#b7d5ff;right:-55px;bottom:0;transform:rotate(45deg);border-radius:10px}.bag{position:absolute;bottom:18px;right:15%;font-size:70px;filter:drop-shadow(0 14px 16px rgba(0,0,0,.25));animation:float 4s ease-in-out infinite reverse}.land-features{background:#fff;color:#17213d;display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:24px 7% 28px}.land-feature{padding:19px;border:1px solid #e3e7ee;border-radius:12px}.land-feature .ico{font-size:24px}.land-feature h3{font-size:13px;margin:8px 0}.land-feature p{font-size:11px;color:#667085;margin:0}.land-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:22px 7%;background:#f5f7fb;color:#17213d}.land-stat{background:#fff;border:1px solid #e3e7ee;border-radius:13px;padding:20px}.land-stat b{font-size:29px}@keyframes float{50%{transform:translateY(-9px)}}@media(max-width:767px){.land-nav{padding:0 18px}.land-links a:not(.register){display:none}.land-hero{grid-template-columns:1fr;padding:45px 20px 35px;text-align:left}.land-hero h1{font-size:36px}.land-visual{height:230px}.land-features,.land-stats{grid-template-columns:1fr;padding-left:18px;padding-right:18px}.bag{right:22%}}
</style></head><body><div class="landing">
<nav class="land-nav"><div class="land-logo">◆ <span>Smart Lost &<br>Found<br>Kampus</span></div><div class="land-links"><a href="#fitur">Tentang</a><a href="temukan.php">Pencarian</a><a href="login.php">Login</a><a class="btn btn-light register" href="register.php">Register</a></div></nav>
<section class="land-hero animate-in"><div><h1>Temukan dan Kembalikan Barang di Kampus.</h1><p>Smart Lost & Found Kampus membantu civitas kampus melaporkan barang hilang, barang ditemukan, mencari laporan, dan mencocokkan data secara cerdas.</p><div class="land-actions"><a class="btn btn-blue" href="<?= $logged?'dashboard.php':'register.php' ?>">Mulai Sekarang</a><a class="btn" style="background:rgba(255,255,255,.12);color:#fff" href="temukan.php">Cari Barang</a></div></div><div class="land-visual"><div class="orb"></div><div class="bag">🎒</div></div></section>
<section id="fitur" class="land-features"><div class="land-feature"><div class="ico">♧</div><h3>Untuk Semua</h3><p>Smart Lost & Found Kampus.</p></div><div class="land-feature"><div class="ico">⌕</div><h3>Terguat</h3><p>Dengan fitur pencarian dan matching.</p></div><div class="land-feature"><div class="ico">✦</div><h3>Smart Matching</h3><p>Temukan kecocokan barang dengan data laporan.</p></div></section>
<section class="land-stats"><div class="land-stat"><b class="animate-number"><?= $lost ?></b><p>Barang hilang terverifikasi</p></div><div class="land-stat"><b class="animate-number"><?= $found ?></b><p>Barang ditemukan terverifikasi</p></div><div class="land-stat"><b class="animate-number"><?= $total ?></b><p>Total laporan aktif</p></div></section>
</div><script src="/assets/app.js"></script></body></html>