<?php
require_once 'config/database.php';require_once 'includes/auth.php';header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');
function support_out($n,$d){http_response_code($n);echo json_encode($d,JSON_UNESCAPED_UNICODE);exit;}
$b=json_decode(file_get_contents('php://input')?:'',true);if(!is_array($b))$b=[];if(!isLoggedIn())support_out(401,['ok'=>false,'error'=>'Silakan login kembali.']);
$uid=(int)$_SESSION['user_id'];$admin=isAdmin();$action=$_GET['action']??'';$id=(int)($_GET['conversation_id']??$b['conversation_id']??0);
if(in_array($action,['send','status'],true)){$token=$_SERVER['HTTP_X_CSRF_TOKEN']??($b['csrf']??'');if(empty($_SESSION['csrf_support'])||!hash_equals($_SESSION['csrf_support'],(string)$token))support_out(403,['ok'=>false,'error'=>'Token keamanan tidak valid. Muat ulang halaman.']);}
if($id<1)support_out(400,['ok'=>false,'error'=>'ID percakapan tidak valid.']);$s=$conn->prepare('SELECT id,user_id,status FROM support_conversations WHERE id=?');$s->bind_param('i',$id);$s->execute();$c=$s->get_result()->fetch_assoc();$s->close();if(!$c)support_out(404,['ok'=>false,'error'=>'Percakapan tidak ditemukan.']);if(!$admin&&(int)$c['user_id']!==$uid)support_out(403,['ok'=>false,'error'=>'Akses ditolak.']);
if($action==='fetch'){$s=$conn->prepare('SELECT id,sender_id,sender_role,message,created_at FROM support_messages WHERE conversation_id=? ORDER BY id ASC LIMIT 500');$s->bind_param('i',$id);$s->execute();$r=$s->get_result();$a=[];while($m=$r->fetch_assoc()){$m['id']=(int)$m['id'];$m['sender_id']=(int)$m['sender_id'];$a[]=$m;}$s->close();support_out(200,['ok'=>true,'status'=>$c['status'],'messages'=>$a]);}
if($action==='send'){if($c['status']!=='OPEN')support_out(409,['ok'=>false,'error'=>'Percakapan sudah ditutup.']);$m=trim((string)($b['message']??''));if($m===''||mb_strlen($m,'UTF-8')>4000)support_out(422,['ok'=>false,'error'=>'Pesan wajib diisi dan maksimal 4000 karakter.']);$role=$admin?'ADMIN':'USER';$s=$conn->prepare('INSERT INTO support_messages(conversation_id,sender_id,sender_role,message) VALUES(?,?,?,?)');$s->bind_param('iiss',$id,$uid,$role,$m);if(!$s->execute())support_out(500,['ok'=>false,'error'=>'Gagal menyimpan pesan.']);$s->close();$s=$conn->prepare('UPDATE support_conversations SET updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->bind_param('i',$id);$s->execute();$s->close();support_out(200,['ok'=>true]);}
if($action==='status'){if(!$admin)support_out(403,['ok'=>false,'error'=>'Khusus admin.']);$status=$b['status']??'';if(!in_array($status,['OPEN','CLOSED'],true))support_out(422,['ok'=>false,'error'=>'Status tidak valid.']);$s=$conn->prepare('UPDATE support_conversations SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->bind_param('si',$status,$id);$ok=$s->execute();$s->close();support_out($ok?200:500,['ok'=>$ok]);}support_out(400,['ok'=>false,'error'=>'Aksi tidak dikenal.']);