<?php
require_once 'config/database.php'; require_once 'includes/auth.php'; require_once 'includes/ui.php'; requireProfile($conn);
$uid=(int)$_SESSION['user_id']; if(empty($_SESSION['csrf_support'])) $_SESSION['csrf_support']=bin2hex(random_bytes(32)); $csrf=$_SESSION['csrf_support'];
$s=$conn->prepare("SELECT id FROM support_conversations WHERE user_id=? AND status='OPEN' ORDER BY updated_at DESC LIMIT 1"); $s->bind_param('i',$uid); $s->execute(); $c=$s->get_result()->fetch_assoc(); $s->close();
if(!$c){$s=$conn->prepare("INSERT INTO support_conversations(user_id,status) VALUES(?,'OPEN')");$s->bind_param('i',$uid);if(!$s->execute())exit('Gagal membuat percakapan.');$cid=(int)$conn->insert_id;$s->close();}else $cid=(int)$c['id'];
$titleForTop='Support';renderHead('Support');renderUserNav('support'); ?>
<div class="content animate-in"><div class="section-head"><div><h1 class="hero-title">Support</h1><p class="muted">Chat langsung dengan admin Smart Lost &amp; Found.</p></div><span class="pill pill-green">Live Support</span></div>
<section class="card" style="max-width:900px;margin:auto"><h2>Chat dengan Admin</h2><div id="msgs" style="height:52vh;min-height:280px;overflow:auto;border:1px solid #ddd;border-radius:14px;padding:14px;display:flex;flex-direction:column;gap:12px"><p class="muted">Memuat pesan...</p></div>
<form id="form" style="display:flex;gap:10px;margin-top:14px;align-items:flex-end"><input id="csrf" type="hidden" value="<?= e($csrf) ?>"><textarea id="msg" class="form-control" rows="2" maxlength="4000" required placeholder="Tulis pesan..." style="flex:1"></textarea><button id="send" class="btn btn-blue" type="submit">Kirim</button></form><p id="feedback" class="muted" role="status"></p></section></div>
<script>(()=>{const id=<?= $cid ?>,csrf=document.getElementById('csrf').value,list=document.getElementById('msgs'),form=document.getElementById('form'),input=document.getElementById('msg'),send=document.getElementById('send'),fb=document.getElementById('feedback');let sig='';function bubble(m){let w=document.createElement('div');w.style.alignSelf=m.sender_role==='USER'?'flex-end':'flex-start';let l=document.createElement('small');l.className='muted';l.textContent=(m.sender_role==='USER'?'Kamu':'Admin')+' · '+m.created_at;let b=document.createElement('div');b.style.cssText='padding:10px 13px;border-radius:12px;white-space:pre-wrap;overflow-wrap:anywhere;background:'+(m.sender_role==='USER'?'#2563eb':'#eee')+';color:'+(m.sender_role==='USER'?'white':'#222');b.textContent=m.message;w.append(l,b);return w}async function load(){try{let r=await fetch('/support-chat.php?action=fetch&conversation_id='+id,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Gagal memuat');let n=(d.messages||[]).map(x=>x.id).join(',');if(n!==sig){list.replaceChildren();if(!d.messages.length){let p=document.createElement('p');p.className='muted';p.textContent='Belum ada pesan. Mulai percakapan di sini.';list.append(p)}else d.messages.forEach(m=>list.append(bubble(m)));list.scrollTop=list.scrollHeight;sig=n}input.disabled=d.status==='CLOSED';send.disabled=input.disabled;if(input.disabled)fb.textContent='Percakapan sudah ditutup admin.'}catch(e){fb.textContent=e.message}}form.onsubmit=async e=>{e.preventDefault();let message=input.value.trim();if(!message)return;send.disabled=true;try{let r=await fetch('/support-chat.php?action=send',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({conversation_id:id,message,csrf})}),d=await r.json();if(!r.ok||!d.ok)throw Error(d.error||'Gagal mengirim');input.value='';fb.textContent='Pesan terkirim';await load()}catch(e){fb.textContent=e.message}finally{send.disabled=input.disabled}};load();setInterval(load,4000)})();</script>
<?php renderFooter(); ?>